# Testing configuration

[tool:pytest]
asyncio_mode = auto
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = -v --strict-markers --tb=short
markers =
    asyncio: marks tests as async (deselect with '-m "not asyncio"')
